<?php
// *** This file is generated by WebsiteBaker Ver.2.8.2
// *** Creation date: 2016-03-22T11:47:26+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 92;
	require('../../../index.php');
// *************************************************
