<?php
// *** This file is generated by WebsiteBaker Ver.2.8.2
// *** Creation date: 2015-06-30T12:49:18+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 65;
	require('../../../index.php');
// *************************************************
